/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */
apply plugin: 'elasticsearch.internal-cluster-test'
apply plugin: 'elasticsearch.internal-java-rest-test'

esplugin {
  name = 'kibana-plugin'
  description = 'Plugin exposing APIs for Kibana system indices'
  classname ='org.elasticsearch.kibana.KibanaPlugin'
  extendedPlugins = ['x-pack-core', 'x-pack-security']
}

dependencies {
  compileOnly(project(':x-pack:plugin:core')) {
    transitive = false
  }
  compileOnly(project(':x-pack:plugin:security')) {
    transitive = false
  }
  clusterModules project(':modules:reindex')
}
